import { readFileSync, writeFileSync } from 'fs';

const existing = JSON.parse(readFileSync('./data/games.json', 'utf8'));
const seen = new Set(existing.map(x => x.appId));

const moreGames = [
  // Platformers & Action
  { name: "Shovel Knight: Treasure Trove", appId: 250760, size: "1.5 GB", tags: ["Online Fix"] },
  { name: "Ori and the Will of the Wisps", appId: 1057090, size: "12.0 GB", tags: ["Online Fix"] },
  { name: "Ori and the Blind Forest", appId: 261570, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Cuphead", appId: 268910, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "Celeste", appId: 504230, size: "1.2 GB", tags: ["Online Fix"] },
  { name: "Hollow Knight: Silksong", appId: 1030300, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Braid Anniversary Edition", appId: 1260280, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "Limbo", appId: 48000, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Inside", appId: 304430, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Little Nightmares", appId: 424840, size: "8.0 GB", tags: ["Online Fix"] },
  { name: "Little Nightmares II", appId: 1293160, size: "9.0 GB", tags: ["Online Fix"] },
  { name: "A Hat in Time", appId: 253230, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Yooka-Laylee", appId: 360830, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Crash Bandicoot N. Sane Trilogy", appId: 731490, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Spyro Reignited Trilogy", appId: 996580, size: "33.0 GB", tags: ["Online Fix"] },
  { name: "Rayman Legends", appId: 274290, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Sonic Generations", appId: 71340, size: "11.0 GB", tags: ["Online Fix"] },
  { name: "Sonic Mania", appId: 584400, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Sonic Frontiers", appId: 1237320, size: "25.0 GB", tags: ["Online Fix"] },
  { name: "Trine 4: The Nightmare Prince", appId: 690640, size: "8.0 GB", tags: ["Online Fix"] },
  // Horror
  { name: "Alien: Isolation", appId: 214490, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Dead Space (2023)", appId: 1693980, size: "50.0 GB", tags: ["Online Fix"] },
  { name: "Dead Space 2", appId: 47780, size: "8.0 GB", tags: ["Online Fix"] },
  { name: "Dead Space 3", appId: 1238860, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Outlast", appId: 238320, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Outlast 2", appId: 414700, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "The Outlast Trials", appId: 1304930, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "SOMA", appId: 351280, size: "13.0 GB", tags: ["Online Fix"] },
  { name: "Penumbra: Overture", appId: 22180, size: "1.5 GB", tags: ["Online Fix"] },
  { name: "Amnesia: Rebirth", appId: 999220, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Visage", appId: 594330, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Layers of Fear", appId: 391720, size: "7.0 GB", tags: ["Online Fix"] },
  { name: "Observer: System Redux", appId: 1386950, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Haunting Ground", appId: 1638340, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Evil Within", appId: 268050, size: "44.0 GB", tags: ["Online Fix"] },
  { name: "The Evil Within 2", appId: 601430, size: "40.0 GB", tags: ["Online Fix"] },
  { name: "Dying Light", appId: 239140, size: "25.0 GB", tags: ["Online Fix"] },
  { name: "Dying Light: The Following", appId: 268520, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Days Gone", appId: 1259420, size: "70.0 GB", tags: ["Online Fix"] },
  { name: "The Last of Us Part I", appId: 1888930, size: "79.0 GB", tags: ["Online Fix"] },
  // Strategy & City Builders
  { name: "Offworld Trading Company", appId: 271890, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Iron Harvest", appId: 1149640, size: "20.0 GB", tags: ["Online Fix"] },
  { name: "Company of Heroes 3", appId: 1677280, size: "50.0 GB", tags: ["Online Fix"] },
  { name: "Company of Heroes 2", appId: 231430, size: "22.0 GB", tags: ["Online Fix"] },
  { name: "Men of War: Assault Squad 2", appId: 244450, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "Command & Conquer Remastered", appId: 1213210, size: "13.0 GB", tags: ["Online Fix"] },
  { name: "Age of Wonders 4", appId: 1669000, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Endless Legend", appId: 289130, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Amplitude", appId: 327510, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "Humankind", appId: 1124300, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Victoria 3", appId: 529340, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Crusader Kings III", appId: 1158310, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Hearts of Iron IV", appId: 394360, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Stellaris", appId: 281990, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "Europa Universalis IV", appId: 236850, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "Imperator: Rome", appId: 859580, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "Surviving Mars", appId: 464920, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Frostpunk 2", appId: 1601580, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Aven Colony", appId: 484900, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Terra Nil", appId: 1593030, size: "1.5 GB", tags: ["Online Fix"] },
  // RPG
  { name: "Pillars of Eternity II: Deadfire", appId: 560130, size: "16.0 GB", tags: ["Online Fix"] },
  { name: "Tyranny", appId: 362960, size: "7.0 GB", tags: ["Online Fix"] },
  { name: "Torment: Tides of Numenera", appId: 272270, size: "12.0 GB", tags: ["Online Fix"] },
  { name: "Pathfinder: Kingmaker", appId: 640820, size: "19.0 GB", tags: ["Online Fix"] },
  { name: "Pathfinder: Wrath of the Righteous", appId: 1184370, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Solasta: Crown of the Magister", appId: 1096930, size: "13.0 GB", tags: ["Online Fix"] },
  { name: "Neverwinter Nights: Enhanced Edition", appId: 704450, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Divinity Original Sin Enhanced", appId: 373420, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Dragon Age: Origins", appId: 47810, size: "13.0 GB", tags: ["Online Fix"] },
  { name: "Dragon Age II", appId: 1238040, size: "9.0 GB", tags: ["Online Fix"] },
  { name: "Dragon Age: Inquisition", appId: 1238820, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Mass Effect Legendary Edition", appId: 1328670, size: "84.0 GB", tags: ["Online Fix"] },
  { name: "Star Wars: Knights of the Old Republic", appId: 32370, size: "1.5 GB", tags: ["Online Fix"] },
  { name: "KOTOR II: The Sith Lords", appId: 208580, size: "4.5 GB", tags: ["Online Fix"] },
  { name: "Jade Empire: Special Edition", appId: 7110, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "The Bard's Tale IV", appId: 499580, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Wasteland 3", appId: 846110, size: "18.0 GB", tags: ["Online Fix"] },
  { name: "Wasteland 2", appId: 240990, size: "7.0 GB", tags: ["Online Fix"] },
  { name: "Shadowrun Returns", appId: 234650, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Shadowrun: Dragonfall", appId: 300550, size: "2.5 GB", tags: ["Online Fix"] },
  // FPS & Shooters
  { name: "Borderlands: The Pre-Sequel", appId: 261640, size: "13.0 GB", tags: ["Online Fix"] },
  { name: "Tiny Tina's Wonderlands", appId: 1286680, size: "40.0 GB", tags: ["Online Fix"] },
  { name: "New World: Aeternum", appId: 1063730, size: "50.0 GB", tags: ["Online Fix"] },
  { name: "Escape from Tarkov", appId: 1271990, size: "50.0 GB", tags: ["Online Fix"] },
  { name: "Battlefield V", appId: 1238810, size: "58.0 GB", tags: ["Online Fix"] },
  { name: "Battlefield 2042", appId: 1517290, size: "64.0 GB", tags: ["Online Fix"] },
  { name: "Battlefield 1", appId: 1238860, size: "49.0 GB", tags: ["Online Fix"] },
  { name: "Titanfall 2", appId: 1237970, size: "35.0 GB", tags: ["Online Fix"] },
  { name: "Medal of Honor: Warfighter", appId: 209870, size: "17.0 GB", tags: ["Online Fix"] },
  { name: "Spec Ops: The Line", appId: 50750, size: "8.0 GB", tags: ["Online Fix"] },
  { name: "Insurgency: Sandstorm", appId: 581320, size: "17.0 GB", tags: ["Online Fix"] },
  { name: "Hell Let Loose", appId: 686810, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Squad", appId: 393380, size: "35.0 GB", tags: ["Online Fix"] },
  { name: "Arma 3", appId: 107410, size: "32.0 GB", tags: ["Online Fix"] },
  { name: "DayZ", appId: 221100, size: "16.0 GB", tags: ["Online Fix"] },
  { name: "Project Zomboid", appId: 108600, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "7 Days to Die", appId: 251570, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "The Forest", appId: 242760, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Sons of the Forest", appId: 1326470, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Green Hell", appId: 815370, size: "4.5 GB", tags: ["Online Fix"] },
  // Simulation & Sports
  { name: "Microsoft Flight Simulator 2024", appId: 2537590, size: "230.0 GB", tags: ["Online Fix"] },
  { name: "Train Sim World 4", appId: 1464790, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Euro Truck Simulator 2", appId: 227300, size: "12.0 GB", tags: ["Online Fix"] },
  { name: "Farming Simulator 22", appId: 1248130, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Farming Simulator 25", appId: 2890550, size: "12.0 GB", tags: ["Online Fix"] },
  { name: "Lawn Mowing Simulator", appId: 1480560, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "PowerWash Simulator", appId: 1290000, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Cooking Simulator", appId: 976620, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "House Flipper", appId: 613100, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "House Flipper 2", appId: 1688820, size: "8.0 GB", tags: ["Online Fix"] },
  { name: "Car Mechanic Simulator 2021", appId: 1190000, size: "8.0 GB", tags: ["Online Fix"] },
  { name: "My Summer Car", appId: 516750, size: "1.0 GB", tags: ["Online Fix"] },
  { name: "Jalopy", appId: 446010, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Bus Simulator 21", appId: 1209700, size: "11.0 GB", tags: ["Online Fix"] },
  { name: "Snowrunner", appId: 1465360, size: "14.0 GB", tags: ["Online Fix"] },
  { name: "MudRunner", appId: 675010, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "Expeditions: A MudRunner Game", appId: 2119370, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Construction Simulator", appId: 1273400, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Wreckfest", appId: 228380, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Assetto Corsa", appId: 244210, size: "17.0 GB", tags: ["Online Fix"] },
  // Adventure & Open World
  { name: "Grand Theft Auto IV", appId: 12210, size: "22.0 GB", tags: ["Online Fix"] },
  { name: "L.A. Noire", appId: 110800, size: "26.0 GB", tags: ["Online Fix"] },
  { name: "Bully: Scholarship Edition", appId: 12200, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Max Payne 3", appId: 204100, size: "35.0 GB", tags: ["Online Fix"] },
  { name: "Mafia: Definitive Edition", appId: 1030840, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Mafia II: Definitive Edition", appId: 50130, size: "17.0 GB", tags: ["Online Fix"] },
  { name: "Mafia III: Definitive Edition", appId: 360430, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Just Cause 3", appId: 225540, size: "42.0 GB", tags: ["Online Fix"] },
  { name: "Just Cause 4", appId: 517630, size: "50.0 GB", tags: ["Online Fix"] },
  { name: "Saints Row IV", appId: 206420, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Saints Row (2022)", appId: 742420, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Sleeping Dogs: Definitive Edition", appId: 307690, size: "14.0 GB", tags: ["Online Fix"] },
  { name: "Watch Dogs", appId: 243470, size: "25.0 GB", tags: ["Online Fix"] },
  { name: "Watch Dogs 2", appId: 447040, size: "25.0 GB", tags: ["Online Fix"] },
  { name: "Watch Dogs: Legion", appId: 742420, size: "33.0 GB", tags: ["Online Fix"] },
  { name: "Far Cry Primal", appId: 371660, size: "20.0 GB", tags: ["Online Fix"] },
  { name: "Far Cry 5", appId: 552520, size: "27.0 GB", tags: ["Online Fix"] },
  { name: "Far Cry New Dawn", appId: 939960, size: "25.0 GB", tags: ["Online Fix"] },
  { name: "Far Cry 6", appId: 1339980, size: "40.0 GB", tags: ["Online Fix"] },
  { name: "Assassins Creed Chronicles: China", appId: 338970, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Assassins Creed III", appId: 208650, size: "15.0 GB", tags: ["Online Fix"] },
  // Indie & Puzzle
  { name: "Portal", appId: 400, size: "0.8 GB", tags: ["Online Fix"] },
  { name: "Portal 2", appId: 620, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "The Witness", appId: 210970, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "The Talos Principle 2", appId: 835960, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Antichamber", appId: 219890, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Manifold Garden", appId: 1049890, size: "1.2 GB", tags: ["Online Fix"] },
  { name: "The Room series", appId: 288160, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Return of the Obra Dinn", appId: 653530, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Obra Dinn", appId: 653530, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Her Story", appId: 368370, size: "0.3 GB", tags: ["Online Fix"] },
  { name: "Firewatch", appId: 383870, size: "4.5 GB", tags: ["Online Fix"] },
  { name: "Abzu", appId: 384190, size: "2.7 GB", tags: ["Online Fix"] },
  { name: "Journey", appId: 638230, size: "1.5 GB", tags: ["Online Fix"] },
  { name: "flower", appId: 966330, size: "1.2 GB", tags: ["Online Fix"] },
  { name: "What Remains of Edith Finch", appId: 501300, size: "5.5 GB", tags: ["Online Fix"] },
  { name: "Gone Home", appId: 232430, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Dear Esther: Landmark Edition", appId: 520720, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "Everybody's Gone to the Rapture", appId: 682570, size: "9.0 GB", tags: ["Online Fix"] },
  { name: "Oxenfree", appId: 388880, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Oxenfree II: Lost Signals", appId: 1614550, size: "4.5 GB", tags: ["Online Fix"] },
  // Fighting
  { name: "Mortal Kombat 11", appId: 976310, size: "65.0 GB", tags: ["Online Fix"] },
  { name: "Injustice 2", appId: 528230, size: "18.0 GB", tags: ["Online Fix"] },
  { name: "Dragon Ball FighterZ", appId: 678950, size: "18.0 GB", tags: ["Online Fix"] },
  { name: "Guilty Gear Strive", appId: 1384160, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "BlazBlue: Centralfiction", appId: 586140, size: "11.0 GB", tags: ["Online Fix"] },
  { name: "Granblue Fantasy Versus", appId: 1090630, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "Skullgirls 2nd Encore", appId: 245170, size: "1.2 GB", tags: ["Online Fix"] },
  { name: "Under Night In-Birth II", appId: 2312960, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "Melty Blood: Type Lumina", appId: 1761130, size: "8.5 GB", tags: ["Online Fix"] },
  { name: "ARMS", appId: 1549280, size: "5.0 GB", tags: ["Online Fix"] },
  // Card & Board Games
  { name: "Tabletop Simulator", appId: 286160, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Slay the Spire", appId: 646570, size: "1.0 GB", tags: ["Online Fix"] },
  { name: "Monster Train", appId: 1102190, size: "0.8 GB", tags: ["Online Fix"] },
  { name: "Inscryption", appId: 1092790, size: "1.2 GB", tags: ["Online Fix"] },
  { name: "Hearthstone", appId: 1463940, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Legends of Runeterra", appId: 1256460, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "Eternal Card Game", appId: 531640, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Shadowverse", appId: 453480, size: "5.5 GB", tags: ["Online Fix"] },
  { name: "Hand of Fate 2", appId: 456670, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Cultist Simulator", appId: 718670, size: "0.6 GB", tags: ["Online Fix"] },
  // Misc & Unique
  { name: "Untitled Goose Game", appId: 837470, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Gang Beasts", appId: 285900, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Human: Fall Flat", appId: 477160, size: "1.0 GB", tags: ["Online Fix"] },
  { name: "Totally Accurate Battle Simulator", appId: 508440, size: "1.5 GB", tags: ["Online Fix"] },
  { name: "People Playground", appId: 1118200, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Clustertruck", appId: 397560, size: "0.3 GB", tags: ["Online Fix"] },
  { name: "Getting Over It with Bennett Foddy", appId: 240720, size: "0.2 GB", tags: ["Online Fix"] },
  { name: "Jump King", appId: 1061090, size: "0.3 GB", tags: ["Online Fix"] },
  { name: "Only Up!", appId: 2381590, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Pogostuck: Rage With Your Friends", appId: 688130, size: "0.2 GB", tags: ["Online Fix"] },
  // More RPGs
  { name: "Witcher 2: Assassins of Kings", appId: 20920, size: "16.0 GB", tags: ["Online Fix"] },
  { name: "Gothic 3", appId: 39810, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "Gothic II Gold", appId: 39810, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Risen 3: Titan Lords", appId: 249230, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "Elex", appId: 411300, size: "13.5 GB", tags: ["Online Fix"] },
  { name: "ELEX II", appId: 1058130, size: "24.0 GB", tags: ["Online Fix"] },
  { name: "Two Worlds II", appId: 7330, size: "5.0 GB", tags: ["Online Fix"] },
  { name: "The Incredible Adventures of Van Helsing", appId: 215530, size: "4.5 GB", tags: ["Online Fix"] },
  { name: "Wolcen: Lords of Mayhem", appId: 424370, size: "15.0 GB", tags: ["Online Fix"] },
  { name: "Last Epoch", appId: 899770, size: "20.0 GB", tags: ["Online Fix"] },
  { name: "Warhammer: Chaosbane", appId: 882090, size: "20.0 GB", tags: ["Online Fix"] },
  { name: "Chronicon", appId: 375480, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Titan Quest Anniversary Edition", appId: 475150, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Victor Vran", appId: 345180, size: "7.0 GB", tags: ["Online Fix"] },
  { name: "Sacred 2 Gold", appId: 225280, size: "10.0 GB", tags: ["Online Fix"] },
  // Sci-Fi
  { name: "System Shock 2", appId: 238210, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "System Shock Remake", appId: 482400, size: "20.0 GB", tags: ["Online Fix"] },
  { name: "Deus Ex: Invisible War", appId: 6910, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Deus Ex: Human Revolution", appId: 28050, size: "7.5 GB", tags: ["Online Fix"] },
  { name: "Deus Ex: Mankind Divided", appId: 337000, size: "23.0 GB", tags: ["Online Fix"] },
  { name: "The Turing Test", appId: 499520, size: "6.5 GB", tags: ["Online Fix"] },
  { name: "Event[0]", appId: 470260, size: "6.0 GB", tags: ["Online Fix"] },
  { name: "Observation", appId: 906100, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Return of the Obra Dinn", appId: 653530, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Tacoma", appId: 382840, size: "6.5 GB", tags: ["Online Fix"] },
  { name: "The Station", appId: 769300, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Deliver Us The Moon", appId: 596970, size: "10.0 GB", tags: ["Online Fix"] },
  { name: "Deliver Us Mars", appId: 1834800, size: "30.0 GB", tags: ["Online Fix"] },
  { name: "The Solus Project", appId: 313630, size: "4.5 GB", tags: ["Online Fix"] },
  { name: "ASTRONEER", appId: 361420, size: "4.0 GB", tags: ["Online Fix"] },
  // More Indie
  { name: "Terraria", appId: 105600, size: "0.2 GB", tags: ["Online Fix"] },
  { name: "Stardew Valley", appId: 413150, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Hades", appId: 1145360, size: "2.5 GB", tags: ["Online Fix"] },
  { name: "Hades II", appId: 1801859, size: "3.5 GB", tags: ["Online Fix"] },
  { name: "Dead Cells", appId: 588650, size: "1.0 GB", tags: ["Online Fix"] },
  { name: "Rogue Legacy 2", appId: 1253920, size: "1.5 GB", tags: ["Online Fix"] },
  { name: "Risk of Rain 2", appId: 632360, size: "3.0 GB", tags: ["Online Fix"] },
  { name: "Enter the Gungeon", appId: 311690, size: "0.8 GB", tags: ["Online Fix"] },
  { name: "Exit the Gungeon", appId: 1209100, size: "0.3 GB", tags: ["Online Fix"] },
  { name: "Binding of Isaac: Afterbirth+", appId: 570660, size: "0.8 GB", tags: ["Online Fix"] },
  { name: "Spelunky 2", appId: 1145360, size: "0.7 GB", tags: ["Online Fix"] },
  { name: "Noita", appId: 881100, size: "1.0 GB", tags: ["Online Fix"] },
  { name: "Neon Abyss", appId: 1145940, size: "1.0 GB", tags: ["Online Fix"] },
  { name: "Curse of the Dead Gods", appId: 1123770, size: "0.6 GB", tags: ["Online Fix"] },
  { name: "Darkest Dungeon II", appId: 1940340, size: "4.0 GB", tags: ["Online Fix"] },
  { name: "Children of Morta", appId: 330020, size: "2.0 GB", tags: ["Online Fix"] },
  { name: "Moonlighter", appId: 606150, size: "0.7 GB", tags: ["Online Fix"] },
  { name: "Graveyard Keeper", appId: 599140, size: "0.5 GB", tags: ["Online Fix"] },
  { name: "Potion Craft: Alchemist Simulator", appId: 1210320, size: "0.4 GB", tags: ["Online Fix"] },
  { name: "Vampire Survivors", appId: 1794680, size: "0.3 GB", tags: ["Online Fix"] },
];

const result = [...existing];
const existingIds = new Set(existing.map(x => x.appId));

for (const g of moreGames) {
  if (!existingIds.has(g.appId)) {
    existingIds.add(g.appId);
    result.push(g);
  }
}

console.log('Final unique count:', result.length);
writeFileSync('./data/games.json', JSON.stringify(result, null, 2));

// Update stats.json
writeFileSync('./data/stats.json', JSON.stringify({ totalGames: result.length }, null, 2));
console.log('stats.json updated');
